/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tyrann3laby;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.BevelBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author torguet
 */
public class MainFrame extends javax.swing.JFrame {
      
    private DrawingPanel panel;
    
    private File savedDirectory = null;
    
    private boolean modified = false;
 
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        panel = new DrawingPanel();

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        
        panel.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent evt) {
                panel.mousePressed(evt);
                modified = true;
            }
            @Override
            public void mouseReleased(MouseEvent evt) {
                panel.mouseReleased(evt);
            }
        });
        
        panel.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent evt) {
                panel.mousePressed(evt);
            }
        });
        

        // add the component to the frame to see it!
        jScrollPane2.setViewportView(panel);
        
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemNew = new javax.swing.JMenuItem();
        jMenuItemLoad = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemQuit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemEmpty = new javax.swing.JCheckBoxMenuItem();
        jMenuItemWall = new javax.swing.JCheckBoxMenuItem();
        jMenuItemDoor = new javax.swing.JMenuItem();
        jMenuItemOther = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItemNew.setText("New");
        jMenuItemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemNew);

        jMenuItemLoad.setText("Load");
        jMenuItemLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoadActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLoad);

        jMenuItemSave.setText("Save");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSave);

        jMenuItemQuit.setText("Quit");
        jMenuItemQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemQuit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Block");

        jMenuItemEmpty.setText("Empty");
        jMenuItemEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEmptyActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemEmpty);

        jMenuItemWall.setSelected(true);
        jMenuItemWall.setText("Wall");
        jMenuItemWall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemWallActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemWall);

        jMenuItemDoor.setText("Simple Door");
        jMenuItemDoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDoorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemDoor);

        jMenuItemOther.setText("Other...");
        jMenuItemOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOtherActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemOther);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoadActionPerformed
        if(modified) {
            Object[] options = {"Yes","No"};
            int n = JOptionPane.showOptionDialog(this,
                    "The labyrinth was modified.\n"+
                    "Are you sure you want to loose your modifications ?",
                    "Quit without saving",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[1]);
             if(n != 0)
                return;
        }
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Labyrinth files", "txt");
        chooser.setFileFilter(filter);
        if(savedDirectory != null) chooser.setCurrentDirectory(savedDirectory);
        int returnVal = chooser.showOpenDialog(this);
        savedDirectory = chooser.getCurrentDirectory();
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            // make sure the file name ends with .txt
            String fileName = chooser.getSelectedFile().getName();
            String filePath = chooser.getSelectedFile().getAbsolutePath();
            if (!fileName.toLowerCase().endsWith(".txt")) {
                fileName += ".txt";
                filePath += ".txt";
            }
            try {
                panel.loadLaby(filePath);
                modified = false;
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,
                    "Error while loading file "+fileName,
                    "File Error",
                    JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jMenuItemLoadActionPerformed

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Labyrinth files", "txt");
        chooser.setFileFilter(filter);
        if(savedDirectory != null) chooser.setCurrentDirectory(savedDirectory);
        int returnVal = chooser.showSaveDialog(this);
        savedDirectory = chooser.getCurrentDirectory();
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            // make sure the file name ends with .txt
            String fileName = chooser.getSelectedFile().getName();
            String filePath = chooser.getSelectedFile().getAbsolutePath();
            if (!fileName.toLowerCase().endsWith(".txt")) {
                fileName += ".txt";
                filePath += ".txt";
            }
            // tests file existence
            File file = new File(filePath);
            if (file.exists()) {
                Object[] options = {"Yes","No"};
                int n = JOptionPane.showOptionDialog(this,
                    "The file "+fileName+" exists.\n"+
                    "Are you sure you want to overwrite it?",
                    "File exists",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[1]);
                if(n != 0)
                    return;
            }
            try {
                panel.saveLaby(filePath);
                modified = false;
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,
                    "Error while saving file "+fileName,
                    "File Error",
                    JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    private void jMenuItemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitActionPerformed
        // TODO add your handling code here:
        if(modified) {
            Object[] options = {"Yes","No"};
            int n = JOptionPane.showOptionDialog(this,
                    "The labyrinth was modified.\n"+
                    "Are you sure you want to loose your modifications ?",
                    "Quit without saving",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[1]);
             if(n != 0)
                return;
        }
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jMenuItemQuitActionPerformed

    private void jMenuItemEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEmptyActionPerformed
        panel.setCurrentValue(0);
        jMenuItemEmpty.setSelected(true);
        jMenuItemWall.setSelected(false);
        jMenuItemDoor.setSelected(false);
        jMenuItemOther.setSelected(false); 
    }//GEN-LAST:event_jMenuItemEmptyActionPerformed

    private void jMenuItemWallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemWallActionPerformed
        panel.setCurrentValue(1);
        jMenuItemEmpty.setSelected(false);
        jMenuItemWall.setSelected(true);
        jMenuItemDoor.setSelected(false);
        jMenuItemOther.setSelected(false); 
    }//GEN-LAST:event_jMenuItemWallActionPerformed

    private void jMenuItemOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOtherActionPerformed
        String s = (String)JOptionPane.showInputDialog(
                            this,
                            "Please type the number for filling the block",
                            "Block type selection",
                            JOptionPane.PLAIN_MESSAGE,
                            null,
                            null,
                            "");

        //If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {
            System.out.println("You typed: " +s);
            try {
                int i = Integer.parseInt(s);
                if(i<0 || i > 255) {
                    JOptionPane.showMessageDialog(this,
                    "Please type in an integer between 0 and 99",
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
                    jMenuItemOther.setSelected(false); 
                } else {
                    panel.setCurrentValue(i);
                    jMenuItemEmpty.setSelected(false);
                    jMenuItemWall.setSelected(false);
                    jMenuItemDoor.setSelected(false);
                    jMenuItemOther.setSelected(true); 
                    jMenuItemOther.setText("Other ("+i+") ...");
                }
            } catch (RuntimeException ex) {
                JOptionPane.showMessageDialog(this,
                    "Please type in an integer between 0 and 99",
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
                jMenuItemOther.setSelected(false);
            }
        } else {
            jMenuItemOther.setSelected(false); 
        }
    }//GEN-LAST:event_jMenuItemOtherActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        jMenuItemQuitActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewActionPerformed
        panel.clear();
    }//GEN-LAST:event_jMenuItemNewActionPerformed

    private void jMenuItemDoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDoorActionPerformed
        panel.setCurrentValue(2);
        jMenuItemEmpty.setSelected(false);
        jMenuItemWall.setSelected(false);
        jMenuItemDoor.setSelected(true);
        jMenuItemOther.setSelected(false); 
    }//GEN-LAST:event_jMenuItemDoorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDoor;
    private javax.swing.JCheckBoxMenuItem jMenuItemEmpty;
    private javax.swing.JMenuItem jMenuItemLoad;
    private javax.swing.JMenuItem jMenuItemNew;
    private javax.swing.JCheckBoxMenuItem jMenuItemOther;
    private javax.swing.JMenuItem jMenuItemQuit;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JCheckBoxMenuItem jMenuItemWall;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
